implovement of deploy

diff --git a/src/driver/docker/deploy b/src/driver/docker/deploy
--- a/src/driver/docker/deploy
+++ b/src/driver/docker/deploy
@@ -18,9 +18,17 @@ NAME=$1
 SRC_FILE=$2
 DEST_PATH=$3
 
+VERCHK=`docker images | awk '{split($3,a,".");if(a[1]>=1&&a[2]>=8)print "t"; else print "f"}'`
+if [ x"$VERCHK" == x"f" ]; then
+	echo "error: it is a older than version 1.8"
+	exit -1
+fi
+
 docker cp $SRC_FILE $NAME:$DEST_PATH
 
-
+if [ $? -eq 0 ]; then
+	echo "deployed file :  $NAME ${DEST_PATH}/${SRC_FILE}"
+fi
 
 
 
