The error check of the device that does not exist is added.

diff --git a/src/driver/docker/net-add b/src/driver/docker/net-add
--- a/src/driver/docker/net-add
+++ b/src/driver/docker/net-add
@@ -77,6 +77,11 @@ if [ x$LXCGATEWAY == x"" ]; then
 fi
 
 if [ x$NETDEV != x"" ]; then
+	ip a show $NETDEV >& /dev/null
+	if [ $? -ne 0 ]; then
+		echo "error: device $NETDEV does not exist."
+		exit -1
+	fi
 	LXCBRIP=`ip a show $NETDEV | awk 'NR==3{print $2}' | awk -F / '{print $1}'`
 	DEVMASK=`ip a show $NETDEV | awk 'NR==3{print $2}' | awk -F / '{print $2}'`
 	if [ x"$LXCBRIP" == x"" ]; then
