The error check of sysgen and clone is corrected.

diff --git a/src/driver/docker/sysgen b/src/driver/docker/sysgen
--- a/src/driver/docker/sysgen
+++ b/src/driver/docker/sysgen
@@ -31,15 +31,15 @@ fi
 
 IMAGE=$2
 
-docker ps | awk '(NR>1){ printf "%s\n",$NF }' | egrep $NAME >& /dev/null
-if [ $? -eq 0 ]; then
+docker ps | awk '(NR>1){ if ($NF == "'$NAME'"){exit -1} }'
+if [ $? -ne 0 ]; then
 	echo "error: already started" $NAME 
 	sleep 5
 	exit -1
 fi
 
-docker ps -a | awk '(NR>1){ printf "%s\n",$NF }' | egrep $NAME >& /dev/null
-if [ $? -eq 0 ]; then
+docker ps -a | awk '(NR>1){ if ($NF == "'$NAME'"){exit -1} }'
+if [ $? -ne 0 ]; then
 	echo "error: already existed" $NAME 
 	sleep 5
 	exit -1
@@ -52,44 +52,7 @@ start_docker() {
 	docker run -it ${OPTCPUSET}=${CPUSET} -c 100 -m 512m \
 	--name $NAME --hostname $NAME \
 	-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
-	--cap-drop=ALL \
-	--cap-add=AUDIT_CONTROL \
-	--cap-add=AUDIT_WRITE \
-	--cap-add=BLOCK_SUSPEND \
-	--cap-add=CHOWN \
-	--cap-add=DAC_OVERRIDE \
-	--cap-add=DAC_READ_SEARCH \
-	--cap-add=FOWNER \
-	--cap-add=FSETID \
-	--cap-add=IPC_LOCK \
-	--cap-add=IPC_OWNER \
-	--cap-add=KILL \
-	--cap-add=LEASE \
-	--cap-add=LINUX_IMMUTABLE \
-	--cap-add=MAC_ADMIN \
-	--cap-add=MAC_OVERRIDE \
-	--cap-add=MKNOD \
-	--cap-add=NET_ADMIN \
-	--cap-add=NET_BIND_SERVICE \
-	--cap-add=NET_BROADCAST \
-	--cap-add=NET_RAW \
-	--cap-add=SETFCAP \
-	--cap-add=SETGID \
-	--cap-add=SETPCAP \
-	--cap-add=SETUID \
-	--cap-add=SYS_ADMIN \
-	--cap-add=SYS_BOOT \
-	--cap-add=SYS_CHROOT \
-	--cap-add=SYS_MODULE \
-	--cap-add=SYS_NICE \
-	--cap-add=SYS_PACCT \
-	--cap-add=SYS_PTRACE \
-	--cap-add=SYS_RAWIO \
-	--cap-add=SYS_RESOURCE \
-	--cap-add=SYS_TIME \
-	--cap-add=SYS_TTY_CONFIG \
-	--cap-add=SYSLOG \
-	--cap-add=WAKE_ALARM \
+	--cap-add=ALL \
 	--privileged \
 	$IMAGE /sbin/init 
 	mkdir -p $LIBDIR/container/$NAME/resource
@@ -102,9 +65,15 @@ start_docker() {
 if [ $FLG_I -eq 1 ]; then
 	start_docker
 else
-	start_docker < /dev/tty >& /dev/null　&
-	stty sane
-	echo "sysgened:" $NAME
+	MSG=`start_docker < /dev/tty 2>&1 ` & 
+	if [ $? -eq 0 ]; then
+		stty sane;
+		echo "sysgened:" $NAME;
+	else
+		stty sane;
+		echo "error: can't sysgened" $NAME
+		echo $MSG
+	fi
 fi
 
 exit 0
