Addition of resource setting function of slot-os

diff --git a/src/slot-os/list b/src/slot-os/list
--- a/src/slot-os/list
+++ b/src/slot-os/list
@@ -10,7 +10,7 @@ SLOTOSDIR=/var/lib/slot-os
 
 usage()
 {
-	echo "usage: list [ SLOT_NUMBER ]"
+	echo "usage: list [ SLOT_NUMBER ...]"
 }
 
 lsdir() {
@@ -57,23 +57,7 @@ list1()
 }
 
 
-if [ $# -ne 1 ]; then
-	usage
-	exit -1
-fi
-
-if [ x"$1" != x"list" ]; then
-	NUM=$1
-	NUM=`echo $NUM | sed -e 's/slot//'` 
-	NUM=`expr $NUM + 0`
-
-	if [ -d $SLOTOSDIR/slot/$NUM ]; then
-		list1 $NUM
-		exit 0
-	else
-		exit -1
-	fi
-fi
+NUMS=$*
 
 if [ ! -d $SLOTOSDIR/slot -o ! -d $SLOTOSDIR/slot/0 ]; then
 	exit -1
@@ -87,10 +71,25 @@ if [ x"$1" == x"list" ]; then
 		list1 $i
 	done | sort -n
 else
-	if [ -d $SLOTOSDIR/slot/$NUM ]; then
-		CNAME=`cat $SLOTOSDIR/slot/$NUM/fulcon`
-		list1 $NUM
-	fi
+	for i in $NUMS
+	do
+		NUM=$i
+		NUM=`echo $NUM | sed -e 's/slot//'` 
+		NUM=`expr $NUM + 1`
+		if [ $? -ne 0 ]; then
+			echo "error: slot $i is not exist"
+			continue
+		else
+			NUM=`expr $NUM - 1`
+		fi
+
+		if [ -d $SLOTOSDIR/slot/$NUM ]; then
+			CNAME=`cat $SLOTOSDIR/slot/$NUM/fulcon`
+			list1 $NUM
+		else
+			echo "error: slot $NUM is not exist"
+		fi
+	done
 fi
 
 exit 0
diff --git a/src/slot-os/resource b/src/slot-os/resource
--- a/src/slot-os/resource
+++ b/src/slot-os/resource
@@ -10,6 +10,7 @@ SLOTOSDIR=/var/lib/slot-os
 usage()
 {
 	echo "usage: resource [-c CPU] [-n CPUSET] [-m MEM] NUMBER ... "
+	echo "usage: resource [-c CPU] [-n CPUSET] [-m MEM] all"
 }
 
 lsdir() {
@@ -38,22 +39,38 @@ shift `expr $OPTIND - 1`
 
 
 SNUMS=$*
+if [ x"$1" == x"all" ]; then
+	SNUMS=`ls $SLOTOSDIR/slot | sort -n`
+fi
+
 for SNUM in $SNUMS
 do
+	expr $SNUM + 1 >& /dev/null
+	if [ $? -ne 0 ]; then
+		echo "error: slot $SNUM is not exist"
+		exit -1
+	fi
+
+	SNUM=`expr $SNUM + 0`
+
 	if [ ! -x $SLOTOSDIR/slot/$SNUM ]; then
 		printf "error: slot%2d is not exist\n" $SNUM
 		RCODE=-1
 		continue
 	fi
+	NAME=`printf "slot%02d" $SNUM`
 
 	if [ $FLG_C -ne 0 ]; then
 		echo $CPU > $SLOTOSDIR/slot/$SNUM/cpu
+		fulcon resource -c $CPU $NAME 
 	fi
 	if [ $FLG_N -ne 0 ]; then
 		echo $CPUSET > $SLOTOSDIR/slot/$SNUM/cpuset
+		fulcon resource -n $CPUSET $NAME
 	fi
 	if [ $FLG_M -ne 0 ]; then
 		echo $MEM > $SLOTOSDIR/slot/$SNUM/memory
+		fulcon resource -m $MEM $NAME
 	fi
 
 done
